### ISSUE TITLE
Swift_TransportException on user registration 

### ISSUE THREAD

**Issue by KnysakPatryk** [GrupaZero/platform#10]
I'm unable to create new user from [lang]/register form. An Swift_TransportException exception is thrown with message: "Cannot send message without a sender address".

**Comment by MateuszUrbanowicz** [comment]
Hi there, you need to set your e-mail username in .env file.

**Comment by jonsh4nnow** [comment]
Fixed, thanks!

**Comment by KnysakPatryk** [comment]
To fix it, set proper .env vars
